### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by mamoon-rasheed** [robinabdullah/POS-ASP.NET-MVC#1]
Dear @robinabdullah its very generous of you for providing such an amazing open source project, thank you for this and hope best of luck for you in future.

I looked at your project and figured out all dependencies but i am stuck in running it because it fails in opening database connection for me.

it will great if this issue is considered.

Thank You so much.

**Comment by robinabdullah** [comment]
Hello Dear,
You can easily generate the database from the edmx file through VS 2015. Thanks.
